### PR TITLE
Upgrade to PureScript v0.12.0

### PR DESCRIPTION
**Pull request by mschristiansen**

### CODE REVIEW

**Comment by mschristiansen** [comment]
@garyb Can we merge? I did a library for [bootstrap v4](https://github.com/mschristiansen/purescript-halogen-bootstrap4), which hasn't been published to pursuit, because of the out-of-memory problem with `pulp publish` on `halogen` packages. Would like to make it more visible. Can I include a link in your README?

**Comment by garyb** [comment]
Actually, do you want to take this library over? I can transfer it to you or something like that, since we don't use it and have no intention of ever doing so again.

**Comment by mschristiansen** [comment]
That's fine. You can transfer. Low maintenance library, so don't mind keeping dependencies recent.

**Comment by garyb** [comment]
Hmm, actually I can't transfer it directly to you, but I've invited you to be a member of this, and you then should be able to transfer it to yourself.

**Comment by mschristiansen** [comment]
I have contacted you on [slack](https://functionalprogramming.slack.com) to discuss.

**Pull request merged**
